version: '2'
services:
  registry:
    image: kimikowang/a8registry:latest
    networks:
      envoymesh:
        aliases:
          - registry
    expose:
      - "8080"
    ports:
      - "31300:8080"

  details-v1:
    image: kimikowang/details-v1:latest
    networks:
      envoymesh:
        aliases:
          - details-v1
    environment:
      - SERVICE_NAME=details
      - SERVICE_VERSION=v1
    expose:
      - "6379"

  ratings-v1:
    image: kimikowang/ratings-v1:latest
    networks:
      envoymesh:
        aliases:
          - ratings-v1
    environment:
      - SERVICE_NAME=ratings
      - SERVICE_VERSION=v1
    expose:
      - "6379"

  reviews-v1:
    image: kimikowang/reviews-v1:latest
    networks:
      envoymesh:
        aliases:
          - reviews-v1
    environment:
      - SERVICE_NAME=reviews
      - SERVICE_VERSION=v1
    expose:
      - "6379"

  reviews-v2:
    image: kimikowang/reviews-v2:latest
    networks:
      envoymesh:
        aliases:
          - reviews-v2
    environment:
      - SERVICE_NAME=reviews
      - SERVICE_VERSION=v2
    expose:
      - "6379"

  reviews-v3:
    image: kimikowang/reviews-v3:latest
    networks:
      envoymesh:
        aliases:
          - reviews-v3
    environment:
      - SERVICE_NAME=reviews
      - SERVICE_VERSION=v3
    expose:
      - "6379"

  productpage-v1:
    image: kimikowang/productpage-v1:latest
    networks:
      envoymesh:
        aliases:
          - productpage-v1
    environment:
      - SERVICE_NAME=productpage
      - SERVICE_VERSION=v1
    expose:
      - "6379"

networks:
  envoymesh: {}
