version: '2'
services:
  ingress:
    image: kimikowang/ingress:latest
    networks:
      envoymesh:
        aliases:
          - gateway
    expose:
      - "8080"
    ports:
      - "31200:8080"

  discovery:
    image: kimikowang/discovery:latest
    networks:
      envoymesh:
        aliases:
          - istio-pilot 
    expose:
      - "8080"
    ports:
      - "8080:8080"
    
  registry:
    image: kimikowang/a8registry:latest
    networks:
      envoymesh:
        aliases:
          - registry
    expose:
      - "8080"
    ports:
      - "31300:8080"

  details-v1:
    image: kimikowang/details-v1:latest
    privileged: true
    networks:
      envoymesh:
        aliases:
          - details
    environment:
      - SERVICE_NAME=details
      - SERVICE_VERSION=v1
    expose:
      - "9080"

  ratings-v1:
    image: kimikowang/ratings-v1:latest
    privileged: true
    networks:
      envoymesh:
        aliases:
          - ratings
    environment:
      - SERVICE_NAME=ratings
      - SERVICE_VERSION=v1
    expose:
      - "9080"


networks:
  envoymesh: {}
